export const FETCH_PROJECTS = 'FETCH_PROJECTS';
export const ADD_NEW_PROJECT = 'ADD_NEW_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';

export const SET_CURRENT_PROJECT_ID = 'SET_CURRENT_PROJECT_ID';
export const REMOVE_CURRENT_PROJECT_ID = 'REMOVE_CURRENT_PROJECT_ID';
export const FETCH_TESTLIST = 'FETCH_TESTLIST';
export const ADD_NEW_TEST = 'ADD_NEW_TEST';
export const DELETE_TEST_PAGE = 'DELETE_TEST_PAGE';

export const DISPLAY_MODAL = 'DISPLAY_MODAL';
export const REMOVE_MODAL = 'REMOVE_MODAL';

export const LOADING_TEST_LIST = 'LOADING_TEST_LIST';
export const REMOVE_TEST_LIST_LOADER = 'REMOVE_TEST_LIST_LOADER';

export const FETCH_SCREENSHOT_URL = 'FETCH_SCREENSHOT_URL';
export const LOADING_SCREENSHOT_SOURCE = 'LOADING_SCREENSHOT_SOURCE';
export const INITIALIZE_SCREENSHOT_STATE = 'INITIALIZE_SCREENSHOT_STATE';

export const LOADING_VISIT_INFO = 'LOADING_VISIT_INFO';
export const FETCH_VISIT_INFO = 'FETCH_VISIT_INFO';
